# Generated by Django 2.2.14 on 2020-08-19 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^[3-9]\\d{9}$')])),
                ('otp', models.CharField(blank=True, max_length=15, null=True)),
                ('count', models.IntegerField(default=0, help_text='Count, Number of OTP sent')),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'phone_otps',
            },
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', ''), ('U', 'User'), ('A', 'Admin'), ('SA', 'Admin'), ('DB', 'Delivery Boy')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^[3-9]\\d{9}$')]),
        ),
    ]
