# Generated by Django 2.2.14 on 2020-08-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0007_auto_20200819_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
