# Generated by Django 2.2.14 on 2020-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0008_auto_20200819_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='images/no_image.png', null=True, upload_to='images/blog_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='images/no_image.png', null=True, upload_to='images/item_images'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='image',
            field=models.FileField(default='images/no_image.png', null=True, upload_to='images/item_category'),
        ),
        migrations.AlterField(
            model_name='itemsubcategory',
            name='image',
            field=models.FileField(default='images/no_image.png', null=True, upload_to='images/item_sub_category'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=1, help_text='Count, Number of OTP sent'),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='image',
            field=models.FileField(default='images/no_image.png', null=True, upload_to='images/spl_items_images'),
        ),
    ]
