# Generated by Django 2.2.14 on 2020-09-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0013_auto_20200906_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='rate',
        ),
    ]
