# Generated by Django 2.2.14 on 2020-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0014_auto_20200907_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
    ]
