# Generated by Django 2.2.14 on 2020-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0015_order_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
