# Generated by Django 2.2.14 on 2020-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0016_auto_20200908_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
