# Generated by Django 2.2.14 on 2020-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0017_auto_20200908_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/page_images')),
            ],
            options={
                'db_table': 'page_images',
            },
        ),
    ]
