# Generated by Django 2.2.14 on 2020-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0018_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_type',
            field=models.CharField(choices=[('%', '%'), ('₹', '₹')], default='%', max_length=1),
        ),
    ]
