# Generated by Django 2.2.14 on 2020-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0019_auto_20200910_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_type',
            field=models.CharField(choices=[(0, 'No discount'), ('%', '%'), ('₹', '₹')], default=0, max_length=1),
        ),
    ]
